name: DDEV Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Setup ddev
      uses: jonaseberle/github-action-setup-ddev@v1.5.0

    - name: Start ddev
      run: ddev start

    - name: Copy .env
      run: ddev php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: ddev php artisan key:generate

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: ddev exec vendor/bin/phpunit
